version: '3.8'

services:
  brcbot:
    image: yourdockerhubuser/brcbot:latest # Replace with your image name from Docker Hub
    container_name: brcbot
    ports:
      - "80:8080" # Maps host port 80 to container port 8080
    environment:
      - GROUPME_BOT_TOKEN=${GROUPME_BOT_TOKEN} # Ensure you have a different .env file or use env variables for prod
    restart: unless-stopped