version: '3.8'

services:
  brcbot:
    image: blakemanternach/brcbotapi:v2.1 
    container_name: brcbot
    ports:
      - "80:8080"
    volumes:
      - ./data:/app/data  # important: persist the DB
    env_file:
        - prod.env
    restart: unless-stopped
