version: '3.8'

services:
  brcbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - test.env
    container_name: brcbot
    ports:
      - "5000:8080" # Maps host port 5000 to container port 80
    restart: unless-stopped