version: '3.8'

services:
  brcbot:
    image: blakemanternach/brcbotapi:latest 
    container_name: brcbot
    ports:
      - "80:8080"
    environment:
      - GROUPME_BOT_TOKEN=${GROUPME_BOT_TOKEN}
    restart: unless-stopped